apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-cluster-pv
spec:
  storageClassName: faster
  capacity:
    storage: 10G
  accessModes:
    - ReadWriteOnce
  gcePersistentDisk:
    pdName: redis-cluster-disk
    fsType: ext4