apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-cluster-pvc
spec:
  storageClassName: faster
  volumeName: redis-cluster-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi